### ISSUE TITLE
error in converting to conll format

### ISSUE THREAD

**Issue by bhavitvyamalik** [verosol/e2e-coref-to-Twitter#1]
Hi,
I was converting to conll format as mentioned in your repository but it's giving error. Let's say for tweet_id `950045570521092096` in new_line (which is saved in json) it's showing:
```
['552_949636905532100608.branch43.', '181', '0', "I've", 'NN', '(ROOT(NP(NP*)', '-', '-', '-', 'King Dayo', '(HANDLE)', '-']
['552_949636905532100608.branch43.', '181', '1', 'I', 'PRP', '(SBAR(S(S(NP*)', 'ppers/exophora/nominal', 'sbj', '-', 'King Dayo', '*', '(6)']
['552_949636905532100608.branch43.', '181', '2', "'ve", 'VBP', '(VP*', '-', '-', '-', 'King Dayo', '*', '-']
['552_949636905532100608.branch43.', '181', '3', 'using', 'VBN', '(VP*', '-', '-', '-', 'King Dayo', '*', '-']
['552_949636905532100608.branch43.', '181', '4', 'one', 'VBG', '(VP*', '-', '-', '-', 'King Dayo', '*', '-']
['552_949636905532100608.branch43.', '181', '5', 'eye', 'CD', '(NP*', '-', '-', '-', 'King Dayo', '(NUMBER)', '-']
['552_949636905532100608.branch43.', '181', '6', 'to', 'NN', '*)', '-', '-', '-', 'King Dayo', '*', '-']
['552_949636905532100608.branch43.', '181', '7', 'follow', 'TO', '(S(VP*', '-', '-', '-', 'King Dayo', '*', '-']
['552_949636905532100608.branch43.', '181', '8', 'your', 'VB', '(VP*', '-', '-', '-', 'King Dayo', '*', '-']
['552_949636905532100608.branch43.', '181', '9', 'tweets', 'PRP$', '(NP*', 'defnp/none/none|ppos/exophora/nominal', 'dir_obj|dir_obj', '-', 'King Dayo', '*', '(5|(9)']
['552_949636905532100608.branch43.', '181', '10', 'and', 'NNS', '*))))))))', '-', '-', '-', 'King Dayo', '*', '5)']
['552_949636905532100608.branch43.', '181', '11', 'they', 'CC', '*', '-', '-', '-', 'King Dayo', '*', '-']
['552_949636905532100608.branch43.', '181', '12', 'inspire', 'PRP', '(S(NP*)', 'ppers/anaphora/nominal', 'sbj', '-', 'King Dayo', '*', '(5)']
['552_949636905532100608.branch43.', '181', '13', 'me', 'VBP', '(VP*', '-', '-', '-', 'King Dayo', '*', '-']
['552_949636905532100608.branch43.', '181', '14', 'nonstop.', 'PRP', '(S(NP*)', 'ppers/anaphora/nominal', 'dir_obj', '-', 'King Dayo', '*', '(6)']
['552_949636905532100608.branch43.', '181', '15', 'nonstop', 'JJ', '(ADJP*))))))', '-', '-', '-', 'King Dayo', '*', '-']
['552_949636905532100608.branch43.', '181', '16', '.', '.', '*))', '-', '-', '-', 'King Dayo', '*', '-']
['552_949636905532100608.branch43.', '181', '0', 'life', 'JJR', '(ROOT(NP(NP*', '-', '-', '-', 'King Dayo', '*', '-']
['552_949636905532100608.branch43.', '181', '1', 'to', 'NN', '*)', '-', '-', '-', 'King Dayo', '*', '-']
['552_949636905532100608.branch43.', '181', '2', 'you', 'TO', '(PP*', '-', '-', '-', 'King Dayo', '*', '-']
['552_949636905532100608.branch43.', '181', '3', 'in', 'PRP', '(NP*))', 'ppers/anaphora/nominal', 'prep_phrase', '-', 'King Dayo', '*', '(9)']
['552_949636905532100608.branch43.', '181', '4', 'success', 'IN', '(PP*', '-', '-', '-', 'King Dayo', '*', '-']
['552_949636905532100608.branch43.', '181', '5', 'and', 'NN', '(NP*', '-', '-', '-', 'King Dayo', '*', '-']
['552_949636905532100608.branch43.', '181', '6', 'good', 'CC', '*', '-', '-', '-', 'King Dayo', '*', '-']
['552_949636905532100608.branch43.', '181', '7', 'health.', 'JJ', '*', '-', '-', '-', 'King Dayo', '*', '-']
['552_949636905532100608.branch43.', '181', '8', 'health', 'NN', '*))', '-', '-', '-', 'King Dayo', '*', '-']
['552_949636905532100608.branch43.', '181', '9', '.', '.', '*))', '-', '-', '-', 'King Dayo', '*', '-']
['552_949636905532100608.branch43.', '181', '0', 'follow', 'RB', '(ROOT(S(ADVP*)', '-', '-', '-', 'King Dayo', '*', '-']
['552_949636905532100608.branch43.', '181', '1', 'back', 'VB', '(VP*', '-', '-', '-', 'King Dayo', '*', '-']
['552_949636905532100608.branch43.', '181', '2', 'Sir.', 'RB', '(PRT*)', '-', '-', '-', 'King Dayo', '*', '-']

Traceback (most recent call last):
  File "make_conll.py", line 147, in <module>
    main()
  File "make_conll.py", line 125, in main
    line_copy[3] = tokenized[0]
IndexError: list index out of range
```
When I checked the tweet I found out it's missing few words in `new_line`, the tweet was `I've been using one eye to follow your tweets and they inspire me nonstop. More life to you in success and good health. Kindly follow back Sir.` Here you can see More and Kindly are missing from new_line. Corresponding lines in `552_949636905532100608.branch43` suggest it was expecting one more word there 
```
552_949636905532100608.branch43.	181	0	_	RB	(ROOT(S(ADVP*)	-	-	-	_	*	-	1_2_0	950045570521092096
552_949636905532100608.branch43.	181	1	_	VB	(VP*	-	-	-	_	*	-	1_2_1	950045570521092096
552_949636905532100608.branch43.	181	2	_	RB	(PRT*)	-	-	-	_	*	-	1_2_2	950045570521092096
552_949636905532100608.branch43.	181	3	_	NNP	(NP*))	defnp/none/none	other/vocative	-	_	*	(9)	1_2_3	950045570521092096
552_949636905532100608.branch43.	181	4	_	.	*))	-	-	-	_	*	-	1_2_4	950045570521092096
```
As a workaround whenever len(tokenized) became 0, I used to stop writing `new_line` in `new_conll` but when I read the coreference labels in generated .conll files I found out they are not related at all. 
The labels were not pointing to corresponding pronouns/nouns. You can see in the example above, 'I' had coref id of (6) whereas for 'me' it should have been (6) but instead of that for 'nonstop' it's showing (6). Same problem with 'tweets' and 'they' in this sentence.

It'd be great if you can provide me a solution to this or your copy of conll files if possible? It's a bit urgent.

Thanks!

**Comment by alestolfo** [comment]
I'm having the same problem with tweet `949797043312107520`. It seems that the CoNLL skeleton was built for more tokens than the ones the tweet actually consists of.
Have you figured out a solution for this issue?

**Comment by bhavitvyamalik** [comment]
Hi @alestolfo,
I did the same as mentioned in my issue. Whenever len(tokenized) became 0, I used to stop writing `new_line` in `new_conll`.
